In [4]:
import pandas as pd
DEPTH = pd.read_hdf("BINANCE_SWAP_BTC-USDT_DEPTH5_2022_02_28.hdf",key="data")
TRADE = pd.read_hdf("BINANCE_SWAP_BTC-USDT_TRADE_2022_02_28.hdf",key="data")

In [10]:
print(DEPTH.shape,'\n',TRADE.shape)

(2521500, 22) 
 (2951820, 4)


In [12]:
DEPTH.columns

Index(['bid1_price', 'bid1_vol', 'ask1_price', 'ask1_vol', 'bid2_price',
       'bid2_vol', 'ask2_price', 'ask2_vol', 'bid3_price', 'bid3_vol',
       'ask3_price', 'ask3_vol', 'bid4_price', 'bid4_vol', 'ask4_price',
       'ask4_vol', 'bid5_price', 'bid5_vol', 'ask5_price', 'ask5_vol', 'time',
       'local_time'],
      dtype='object')

In [19]:
DEPTH.head(5)

bid1_price  bid1_vol  ask1_price  ask1_vol  bid2_price  bid2_vol  \
0     37672.6     0.020     37672.7     0.126     37672.1     0.180   
1     37672.6     0.020     37672.7     0.126     37672.1     0.082   
2     37672.6     0.020     37672.7     0.126     37672.1     0.180   
3     37672.6     0.020     37672.7     0.126     37672.1     0.180   
4     37672.1     0.176     37672.2     1.418     37672.0     1.151   

   ask2_price  ask2_vol  bid3_price  bid3_vol  ...  bid4_price  bid4_vol  \
0     37674.6     0.007     37672.0     1.151  ...     37670.9     0.333   
1     37674.6     0.007     37672.0     1.151  ...     37670.9     0.333   
2     37674.6     0.279     37672.0     1.151  ...     37670.9     0.333   
3     37674.5     0.011     37672.0     1.151  ...     37670.9     0.333   
4     37672.5     0.216     37670.9     0.333  ...     37670.0     0.001   

   ask4_price  ask4_vol  bid5_price  bid5_vol  ask5_price  ask5_vol  \
0     37675.0     1.000     37670.7     0.014     37675.1     0.359   
1     37675.0     1.000     37670.2     0.020     37675.1     0.359   
2     37675.0     1.000     37670.2     0.020     37675.1     0.359   
3     37674.9     0.067     37670.2     0.020     37675.0     1.000   
4     37674.4     0.067     37669.4     0.014     37674.5     0.011   

            time     local_time  
0  1646006398926  1646006398926  
1  1646006398959  1646006398959  
2  1646006398993  1646006398993  
3  1646006399029  1646006399029  
4  1646006399067  1646006399067  

[5 rows x 22 columns]

In [17]:
TRADE.head(5)

price    vol           time     local_time
0  37672.1  0.040  1646006399296  1646006399296
1  37672.0 -0.154  1646006399522  1646006399522
2  37672.0 -0.197  1646006399673  1646006399673
3  37672.0 -1.425  1646006399826  1646006399826
4  37672.0 -0.017  1646006399982  1646006399982

In [13]:
TRADE.columns

Index(['price', 'vol', 'time', 'local_time'], dtype='object')

In [2]:
import numpy as np
P = np.array([[1/2,1/2,0],[1/4,1/2,1/4],[0,1/2,1/2]])#转移概率矩阵
a_0 = [1,0,0]# 初始状态
for i in range(100):
    a_0 = np.dot(a_0,P)
    print(a_0)

[0.5 0.5 0. ]
[0.375 0.5   0.125]
[0.3125 0.5    0.1875]
[0.28125 0.5     0.21875]
[0.265625 0.5      0.234375]
[0.2578125 0.5       0.2421875]
[0.25390625 0.5        0.24609375]
[0.25195312 0.5        0.24804688]
[0.25097656 0.5        0.24902344]
[0.25048828 0.5        0.24951172]
[0.25024414 0.5        0.24975586]
[0.25012207 0.5        0.24987793]
[0.25006104 0.5        0.24993896]
[0.25003052 0.5        0.24996948]
[0.25001526 0.5        0.24998474]
[0.25000763 0.5        0.24999237]
[0.25000381 0.5        0.24999619]
[0.25000191 0.5        0.24999809]
[0.25000095 0.5        0.24999905]
[0.25000048 0.5        0.24999952]
[0.25000024 0.5        0.24999976]
[0.25000012 0.5        0.24999988]
[0.25000006 0.5        0.24999994]
[0.25000003 0.5        0.24999997]
[0.25000001 0.5        0.24999999]
[0.25000001 0.5        0.24999999]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.25 0.5  0.25]
[0.

In [5]:
import numpy as np
P = np.array([[1,0,0,0,0,0],
              [0,1,0,0,0,0],
              [1/4,0,1/2,0,1/4,0],
              [0,0,0,0,1,0],
              [1/16,1/16,1/4,1/8,1/4,1/4],
              [0,1/4,0,0,1/4,1/2]])
a_0 = [1/6,1/6,1/6,1/6,1/6,1/6] # 初始状态
for i in range(100):
    a_0 = np.dot(a_0,P)
    print(a_0)

[0.21875    0.21875    0.125      0.02083333 0.29166667 0.125     ]
[0.26822917 0.26822917 0.13541667 0.03645833 0.15625    0.13541667]
[0.31184896 0.31184896 0.10677083 0.01953125 0.14322917 0.10677083]
[0.34749349 0.34749349 0.08919271 0.01790365 0.10872396 0.08919271]
[0.37658691 0.37658691 0.07177734 0.01359049 0.08968099 0.07177734]
[0.40013631 0.40013631 0.05830892 0.01121012 0.07189941 0.05830892]
[0.41920726 0.41920726 0.04712931 0.00898743 0.05833944 0.04712931]
[0.4346358  0.4346358  0.03814952 0.00729243 0.04713694 0.03814952]
[0.44711924 0.44711924 0.03085899 0.00589212 0.03815142 0.03085899]
[0.45721845 0.45721845 0.02496735 0.00476893 0.03085947 0.02496735]
[0.465389   0.465389   0.02019854 0.00385743 0.02496747 0.02019854]
[0.47199911 0.47199911 0.01634114 0.00312093 0.02019857 0.01634114]
[0.4773468  0.4773468  0.01322021 0.00252482 0.01634115 0.01322021]
[0.48167318 0.48167318 0.01069539 0.00204264 0.01322022 0.01069539]
[0.48517329 0.48517329 0.00865275 0.00165253 0.0